language: node_js
node_js:
  - "12.16.1"
cache:
  directories:
  - node_modules
script:
  - npm test
  - CI=false npm run build
notifications:
  email:
    recipients:
      - naomixzdu@gmail.com
    on_success: always
    on_failure: always
